var Items = {
    T1: ['Cooked Turkey Chop', 'Copper Ingot', 'Copper Plate', 'Copper Wire', 'Glass Panes', 'Glass', 'Ornate Wood Table', 'Pressurized Wood', 'Stone Bricks', 'Stone Slab', 'Stone Tiles', 'Turkey Chop', 'Turkey Slices', 'Wood Boards', 'Wood Table'],
    T2: ['Advanced Circuit', 'Basic Circuit', 'Copper Gear', 'Framed Glass', 'Gold Ingot', 'Gold Plate', 'Gold Wire', 'Golden Turkey', 'Hardwood Boards', 'Hardwood Table', 'Iron Gear', 'Iron Ingot', 'Iron Plate', 'Iron Wire', 'Mechanical Assembly', 'Pressurized Hardwood', 'Reinforced Glass'],
    T3: ['Cut Diamond', 'Diamond Charm', 'Fuel Rod', 'Living Alloy Gear', 'Living Alloy', 'Living Composite', 'Mutant Turkey', 'Pressurized Superwood', 'Reactor Core', 'Resinite Fibers', 'Resinite Gear', 'Resinite Ingot', 'Resinite Mesh', 'Resinite Plate', 'Resinite Wire', 'Superwood Boards', 'Superwood Table', 'Titanium Gear', 'Titanium Glass', 'Titanium Ingot', 'Titanium Plate', 'Titanium Wire', 'Uranium Ingot'],
    T4: ['Advanced Fuel Rod', 'Advanced Mechanical Assembly', 'Blue Ultra Boards', 'Bluemetal Gear', 'Bluemetal Ingot', 'Bluemetal Plate', 'Bluemetal Wire', 'Bluesteel Gear', 'Bluesteel Ingot', 'Bluesteel Plate', 'Fire Glass', 'Frozen Turkey Chop', 'Greater Lava Charm', 'Ice Charm', 'Ice Gem', 'Ice Glass', 'Lava Gem', 'Lesser Lava Charm', 'Obsidian Alloy Gear', 'Obsidian Alloy Plate', 'Obsidian Charm', 'Obsidian Gem', 'Pressurized Ultrawood', 'Red Ultra Boards', 'Redmetal Gear', 'Redmetal Ingot', 'Redmetal Plate', 'Redmetal Wire', 'Redsteel Gear', 'Redsteel Ingot', 'Redsteel Plate', 'Tungsten Gear', 'Tungsten Ingot', 'Tungsten Plate', 'Tungsten Wire', 'Ultrawood Boards', 'Ultrawood Table'],
    T5: ['Advanced Energy Core', 'Composite Plate', 'Concentrated Energy Gem', 'Elite Energy Core', 'Energy Gem', 'Osmium Gear', 'Osmium Gravel', 'Osmium Ingot', 'Osmium Mechanism', 'Osmium Pipe', 'Osmium Plate', 'Osmium Ring', 'Osmium Screw', 'Osmium Wire', 'Petrified Boards', 'Petrified Table', 'Pressurized Petrified Wood', 'Reinforced Osmium Plate', 'Reinforced Shroomite Plate', 'Reinforced Shroomsteel Plate', 'Reinforced Strangesteel Plate', 'Reinforced Trimetal Plate', 'Reinforced Weird Plate', 'Reinforced Weirdsteel Plate', 'Shroomite Gear', 'Shroomite Gravel', 'Shroomite Ingot', 'Shroomite Mechanism', 'Shroomite Pipe', 'Shroomite Plate', 'Shroomite Ring', 'Shroomite Screw', 'Shroomite Wire', 'Shroomsteel Energy Core', 'Shroomsteel Gear', 'Shroomsteel Ingot', 'Shroomsteel Mechanism', 'Shroomsteel Pipe', 'Shroomsteel Plate', 'Shroomsteel Ring', 'Shroomsteel Screw', 'Shroomsteel Wire', 'Strangesteel Energy Core', 'Strangesteel Gear', 'Strangesteel Ingot', 'Strangesteel Mechanism', 'Strangesteel Plate', 'Strangesteel Ring', 'Strangesteel Screw', 'Strangesteel Wire', 'Trimetal Gear', 'Trimetal Ingot', 'Trimetal Mechanism', 'Trimetal Pipe', 'Trimetal Plate', 'Trimetal Reactor', 'Trimetal Ring', 'Trimetal Screw', 'Trimetal Wire', 'Turkey Roll', 'Weird Gear', 'Weird Gravel', 'Weird Ingot', 'Weird Mechanism', 'Weird Pipe', 'Weird Plate', 'Weird Ring', 'Weird Screw', 'Weird Wire', 'Weirdsteel Energy Core', 'Weirdsteel Gear', 'Weirdsteel Ingot', 'Weirdsteel Mechanism', 'Weirdsteel Pipe', 'Weirdsteel Plate', 'Weirdsteel Ring', 'Weirdsteel Screw', 'Weirdsteel Wire'],

    T6: [],
}
var ItemCosts = {
    T1: {
        'Cooked Turkey Chop': '$600',
        'Copper Ingot': '$85',
        'Copper Plate': '$100',
        'Copper Wire': '$225',
        'Glass Panes': '$85',
        'Glass': '$105',
        'Ornate Wood Table': '$30k',
        'Pressurized Wood': '$65',
        'Stone Bricks': '$45',
        'Stone Slab': '$25',
        'Stone Tiles': '$35',
        'Turkey Chop': '$100',
        'Turkey Slices': '$100',
        'Wood Boards': '$25',
        'Wood Table': '$2.2k',
    },
    T2: {
        'Advanced Circuit': '$47.5k',
        'Basic Circuit': '$3.95k',
        'Copper Gear': '$3.55k',
        'Framed Glass': '$635',
        'Gold Ingot': '$1.73k',
        'Gold Plate': '$2.55k',
        'Gold Wire': '$9.5k',
        'Golden Turkey': '$48.5k',
        'Hardwood Boards': '$850',
        'Hardwood Table': '$7.5k',
        'Iron Gear': '$10.75k',
        'Iron Ingot': '$1.45k',
        'Iron Plate': '$1.65k',
        'Iron Wire': '$2.8k',
        'Mechanical Assembly': '$48.5k',
        'Pressurized Hardwood': '$1.18k',
        'Reinforced Glass': '$35.5k',
    },
    T3: {
        'Cut Diamond': '$1.98m',
        'Diamond Charm': '$58.65m',
        'Fuel Rod': '$1.76m',
        'Living Alloy': '$63m',
        'Living Alloy Gear': '$72.5m',
        'Living Composite': '$65.55m',
        'Mutant Turkey': '$63m',
        'Pressurized Superwood': '$295k',
        'Reactor Core': '$58.25m',
        'Resinite Fibers': '$1.9m',
        'Resinite Gear': '$10m',
        'Resinite Ingot': '$625k',
        'Resinite Mesh': '$15.5m',
        'Resinite Plate': '$915k',
        'Resinite Wire': '$1.45m',
        'Superwood Boards': '$185k',
        'Superwood Table': '$8.87m',
        'Titanium Gear': '$12.29m',
        'Titanium Glass': '$46.5m',
        'Titanium Ingot': '$685k',
        'Titanium Plate': '$930k',
        'Titanium Wire': '$1.17m',
        'Uranium Ingot': '$715k',
    },
    T4: {
        'Advanced Fuel Rod': '$10.56t',
        'Advanced Mechanical Assembly': '$75.56t',
        'Blue Ultra Boards': '$25.56t',
        'Bluemetal Gear': '$1.26t',
        'Bluemetal Ingot': '$15.5b',
        'Bluemetal Plate': '$18.5b',
        'Bluemetal Wire': '$88.5b',
        'Bluesteel Gear': '$1.56t',
        'Bluesteel Ingot': '$25.5b',
        'Bluesteel Plate': '$30.5b',
        'Fire Glass': '$19.56t',
        'Frozen Turkey Chop': '$75.56t',
        'Greater Lava Charm': '$25.56t',
        'Ice Charm': '$23.36t',
        'Ice Gem': '$135.5b',
        'Ice Glass': '$19.56t',
        'Lava Gem': '$135.5b',
        'Lesser Lava Charm': '$1.56t',
        'Obsidian Alloy Gear': '$30.56t',
        'Obsidian Alloy Plate': '$25.56t',
        'Obsidian Charm': '$75.56t',
        'Obsidian Gem': '$22.56t',
        'Pressurized Ultrawood': '$9.12b',
        'Red Ultra Boards': '$25.56t',
        'Redmetal Gear': '$1.26t',
        'Redmetal Ingot': '$15.5b',
        'Redmetal Plate': '$18.5b',
        'Redmetal Wire': '$88.5b',
        'Redsteel Gear': '$1.56t',
        'Redsteel Ingot': '$25.5b',
        'Redsteel Plate': '$30.5b',
        'Tungsten Gear': '$1.16t',
        'Tungsten Ingot': '$12.5b',
        'Tungsten Plate': '$15.5b',
        'Tungsten Wire': '$75b',
        'Ultrawood Boards': '$6.12b',
        'Ultrawood Table': '$855.5b',
    },
    T5: {
        'Advanced Energy Core': '$2.85sx',
        'Composite Plate': '$900qn',
        'Concentrated Energy Gem': '$550qd',
        'Elite Energy Core': '$5.35sx',
        'Energy Gem': '$220qd',
        'Osmium Gear': '$646.8qd',
        'Osmium Gravel': '$85qd',
        'Osmium Ingot': '$168qd',
        'Osmium Mechanism': '$1.78qn',
        'Osmium Pipe': '$663.6qd',
        'Osmium Plate': '$252qd',
        'Osmium Ring': '$1.74qn',
        'Osmium Screw': '$1.76qn',
        'Osmium Wire': '$327.6qd',
        'Petrified Boards': '$50qd',
        'Petrified Table': '$350qd',
        'Pressurized Petrified Wood': '$160qd',
        'Reinforced Osmium Plate': '$1.77qn',
        'Reinforced Shroomite Plate': '$1.48qn',
        'Reinforced Shroomsteel Plate': '$14.77qn',
        'Reinforced Strangesteel Plate': '$14.77qn',
        'Reinforced Trimetal Plate': '$221.55qn',
        'Reinforced Weird Plate': '$1.18qn',
        'Reinforced Weirdsteel Plate': '$14.77qn',
        'Shroomite Gear': '$539qd',
        'Shroomite Gravel': '$80qd',
        'Shroomite Ingot': '$140qd',
        'Shroomite Mechanism': '$1.48qn',
        'Shroomite Pipe': '$553qd',
        'Shroomite Plate': '$210qd',
        'Shroomite Ring': '$1.45qn',
        'Shroomite Screw': '$1.46qn',
        'Shroomite Wire': '$273qd',
        'Shroomsteel Energy Core': '$650qn',
        'Shroomsteel Gear': '$5.39qn',
        'Shroomsteel Ingot': '$1.4qn',
        'Shroomsteel Mechanism': '$14.84qn',
        'Shroomsteel Pipe': '$5.53qn',
        'Shroomsteel Plate': '$2.1qn',
        'Shroomsteel Ring': '$14.49qn',
        'Shroomsteel Screw': '$14.63qn',
        'Shroomsteel Wire': '$2.73qn',
        'Strangesteel Energy Core': '$650qn',
        'Strangesteel Gear': '$5.39qn',
        'Strangesteel Ingot': '$1.4qn',
        'Strangesteel Mechanism': '$14.84qn',
        'Strangesteel Plate': '$5.53qn',
        'Strangesteel Plate': '$2.1qn',
        'Strangesteel Ring': '$14.49qn',
        'Strangesteel Screw': '$14.63qn',
        'Strangesteel Wire': '$2.73qn',
        'Trimetal Gear': '$80.85qn',
        'Trimetal Ingot': '$21qn',
        'Trimetal Mechanism': '$222.6qn',
        'Trimetal Pipe': '$82.95qn',
        'Trimetal Plate': '$31.5qn',
        'Trimetal Reactor': '$90sx',
        'Trimetal Ring': '$217.35qn',
        'Trimetal Screw': '$219.45qn',
        'Trimetal Wire': '$40.95qn',
        'Turkey Roll': '$9sx',
        'Weird Gear': '$431.2qd',
        'Weird Gravel': '$80qd',
        'Weird Ingot': '$112qd',
        'Weird Mechanism': '$1.19qn',
        'Weird Pipe': '$442.4qd',
        'Weird Plate': '$168qd',
        'Weird Ring': '$1.16qn',
        'Weird Screw': '$1.17qn',
        'Weird Wire': '$128.4qd',
        'Weirdsteel Energy Core': '$650qn',
        'Weirdsteel Gear': '$5.39qn',
        'Weirdsteel Ingot': '$1.4qn',
        'Weirdsteel Mechanism': '$14.84qn',
        'Weirdsteel Pipe': '$5.53qn',
        'Weirdsteel Plate': '$2.1qn',
        'Weirdsteel Ring': '$14.49qn',
        'Weirdsteel Screw': '$14.63qn',
        'Weirdsteel Wire': '$2.73qn',
    }
}

function ItemListToPageMenu(tier) {
    let ItemList = Items[tier]
    for (let i = 0; i < ItemList.length; i++) {
        let NewElement = document.createElement("div")
        NewElement.classList.add("menu-item")

        let NewText = document.createElement("div")
        NewText.textContent = ItemList[i]
        
        let NewImage = document.createElement("img")
        NewImage.src = `items/${tier}/${ItemList[i]}.png`
        
        let NewUnderText = document.createElement("div")
        NewUnderText.textContent = ItemCosts[tier][ItemList[i]]

        NewElement.onclick = function() {
            window.open(`tree/index.html?item=${ItemList[i]}`, '_self')
        }
        
        NewElement.appendChild(NewText)
        NewElement.appendChild(NewImage)
        NewElement.appendChild(NewUnderText)
        document.querySelector(`.${tier}-menu`).appendChild(NewElement)
    }
}
ItemListToPageMenu("T1")
ItemListToPageMenu("T2")
ItemListToPageMenu("T3")
ItemListToPageMenu("T4")
ItemListToPageMenu("T5")